## Basics of Python

**Name: ** Grant Lee

In [43]:
# This is a comment

In [44]:
# Creating Variables

var1='Hello World'

In [45]:
# You can print in Jupyter Notebooks without a print statement.
var1

'Hello World'

In [46]:
# Or with one if it is not the last line
print(var1)

Hello World


In [47]:
# Lets talk about lists

list1=[0,1,2,3,4,5,6,7,8,9]

In [48]:
print('fifth index:',list1[5])

print("4 Through 7:",list1[4:8])

print("Before appending:", list1)

list1.append(10)

print("After appending 10 to the list: ", list1)

fifth index: 5
4 Through 7: [4, 5, 6, 7]
Before appending: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
After appending 10 to the list:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [49]:
# for loops and if statments are made very easy in python, just follow this example
newArray=[1,2,3,4,5,6,7,8,9]
for x in newArray:
    if x%2 == 0:
        print(x,'is even')
    else:
        print(x,'is odd')

1 is odd
2 is even
3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd


In [50]:
# list comprehention is a little more difficult and isn't necessary, but if you know how to do it, it saves time

## For x in the range of (0,100), if x is even, then input into the array

allEven=[x for x in range(0,100) if x%2==0]
print(allEven)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


# 1. Put all the prime numbers from 1 to 100 in a list (Save it as a variable called 'prime_numbers'): 

In [51]:
#### TODO: Complete this part ####

prime_numbers = [x for x in range (1,101) if all([x%y != 0 for y in range(2,x)])]


[1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [99]:
# Make Array into npArray

np.asarray(prime_numbers)

array([ 1,  2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53,
       59, 61, 67, 71, 73, 79, 83, 89, 97])

## Introduction to Numpy

In [52]:
# Importing Numpy
import numpy as np

In [53]:
# Creating an npArray
arr1=np.array([1,2,3]) #seperate with commas

In [54]:
print(arr1)

[1 2 3]


In [106]:
# Creating a 2d npArray
arr2=np.array([[1,2,3],[4,5,6]]) 

In [56]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [57]:
# Get the dimensions of the array (row, column)
arr2.shape 

(2, 3)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Different ways to create ndarrays:
</p>

In the code below, we create a number of different sized arrays with different shapes and values.  Numpy has some built in methods (listed below) which help us quickly and easily create multidimensional arrays with pre-filled values.

**np.zeros((dimensions))** creates an array of zeros with the specified dimensions

**np.full((dimensions), value)** creates an array with the specified dimensions where every element is the specified value

**np.random.random(dimensions)** generates an array of random floating-point values between 0 and 1

In [58]:
# create a 3x4 array of zeros
ex1 = np.zeros((3, 4))      
print(ex1)    

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [59]:
# create a 2x3 array filled with 9.0
ex2 = np.full((2,3), 9.0)  
print(ex2)   

[[ 9.  9.  9.]
 [ 9.  9.  9.]]


In [60]:
# create a 2x3 array of random floating-point numbers between 0 and 1
ex3 = np.random.random((2,3))
print(ex3)    

[[ 0.74125218  0.70967871  0.33420057]
 [ 0.47286495  0.37865278  0.17810804]]


In [61]:
ex3[0] #this first index if the first row

array([ 0.74125218,  0.70967871,  0.33420057])

In [62]:
ex4=np.random.randint(1,10,(5,10)) #(low,high-exclusive,shape)
print(ex4)

[[4 1 5 7 9 9 3 9 9 1]
 [3 9 3 8 9 6 6 7 5 1]
 [6 4 7 4 3 5 1 1 5 9]
 [2 5 6 5 4 8 9 7 2 8]
 [6 8 6 1 4 3 2 3 2 6]]


In [107]:
# Get the 3rd row of list ex4
ex4[2]

array([6, 4, 7, 4, 3, 5, 1, 1, 5, 9])

In [108]:
# Get the median of the 2nd row of ex4
np.median(ex4[1])

6.0

## Mathematical Operations 

In [65]:
arr1=np.array([2,4,6,8,10])

In [66]:
print(arr1)

[ 2  4  6  8 10]


In [67]:
# Take the sqrt of each element of arr1
print(np.sqrt(arr1))

[ 1.41421356  2.          2.44948974  2.82842712  3.16227766]


In [109]:
# Get the maximum element of arr1
np.max(arr1)

10

In [69]:
# Get the minimum element of arr1
np.min(arr1)

2

In [110]:
# Get the median element of arr1
np.median(arr1)

6.0

In [71]:
# Get the standard deviation of arr1
np.std(arr1)

2.8284271247461903

In [111]:
# Add 1 to each element of arr1
arr1+1

array([ 3,  5,  7,  9, 11])

In [112]:
# Multiply 2 to each element of arr1
arr1*2

array([ 4,  8, 12, 16, 20])

In [113]:
# Obtain elements from index 2 till end
print(arr1[2:])

[ 6  8 10]


In [114]:
# Obtain only unique elements of array of interest
np.unique(np.array([1,1,1,1,2]))

array([1, 2])

In [115]:
arr2=np.array([3,6,9,12,15])

In [116]:
# Add two arrays together
np.add(arr1,arr2)

array([ 5, 10, 15, 20, 25])

In [117]:
# Can also add two arrays this way
arr1+arr2

array([ 5, 10, 15, 20, 25])

In [118]:
# Obtain the dot product of two arrays 
arr1.dot(arr2)

330

In [119]:
# Obtain the sum of all elements in array of interest
np.sum(arr1)

30

# 2. Create an random integer array with a min of 1, max of 10, and shape of (20,10) so 20 rows and 10 columns. Then for each row, sum the random integers and add all the sums to a list called 'random_sums'. 

In [120]:
#### TODO: Complete this part 

random_sum_list = np.random.randint(1,10,(20,10))
random_sums = []
for x in random_sum_list:
    random_sums.append(np.sum(x))

## Sets

In [122]:
arr1=np.array([x for x in range(0,50) if x%5 > 2]) #All remainders from 5 greater than 2 to 49
arr2=np.array([x for x in range(0,50) if x%7 > 3]) #All remainders from 7 greater than 3 to 49

print('array 1:',arr1)
print('array 2:',arr2)

array 1: [ 3  4  8  9 13 14 18 19 23 24 28 29 33 34 38 39 43 44 48 49]
array 2: [ 4  5  6 11 12 13 18 19 20 25 26 27 32 33 34 39 40 41 46 47 48]


In [41]:
union=np.union1d(arr1,arr2) #in either arr1 or arr2
print('union:',union)

union: [ 3  4  5  6  8  9 11 12 13 14 18 19 20 23 24 25 26 27 28 29 32 33 34 38 39
 40 41 43 44 46 47 48 49]


In [42]:
intersect=np.intersect1d(arr1,arr2) #in both arr1 and arr2
print('intersect:',intersect)

intersect: [ 4 13 18 19 33 34 39 48]


## Reshaping

In [143]:
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [144]:
arr1.reshape(2,-1) #first number is the number of rows, -1 automatically selects the number that works

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [145]:
np.transpose(arr1) #switches the axis

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# 3. Find the numbers that are in both 'prime_numbers' and 'random_sums' and put them in an array called 'both'

In [130]:
#### TODO: Complete this part ####
#### can be done in one line! ####
both = np.intersect1d(prime_numbers,random_sums)