# Introduction to Numpy

In [2]:
# importing Numpy
import numpy as np

In [3]:
arr1 = np.array([1,2,3]) 

In [4]:
print(arr1)

[1 2 3]


In [6]:
arr2=np.array([[1,2,3],[4,5,6]])

In [7]:
print(arr2)


[[1 2 3]
 [4 5 6]]


In [10]:
# create a 2x3 array of zeros

ex1 = np.zeros([3,4])
print(ex1)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [12]:
# Create a 2x3 array filled with 9,0
ex2 = np.full((2,3),9.0)
print(ex2)

[[ 9.  9.  9.]
 [ 9.  9.  9.]]


In [ ]:
### Create a 2x3 array of random floating point numbers between 0 and 1
ex3 = np.random.random((2,3))
print(ex3)

In [15]:
ex3[0]

array([ 0.56944695,  0.99540871,  0.64654755])

In [ ]:
ex3[1]

In [18]:
ex4 = np.random.randint(1,10,(5,10)) #(Low, high-exclusive, shape)
print(ex4)

[[4 5 5 8 8 2 3 9 9 1]
 [3 3 8 7 7 7 9 7 4 2]
 [8 6 7 1 1 7 7 8 9 3]
 [6 1 4 5 1 2 7 9 9 9]
 [6 7 8 7 5 5 4 1 5 4]]


In [21]:
ex4[4]

array([6, 7, 8, 7, 5, 5, 4, 1, 5, 4])

In [23]:
# Get the median of the function
np.median(ex4[4])

5.0

# Mathematical Operations




In [24]:
np.min(arr1)

1

In [25]:
arr1 + 1

array([2, 3, 4])